import '../../game-auth.js';
import * as CANNON from 'cannon-es';
import * as THREE from 'three';
import { OrbitControls } from 'OrbitControls';
import { OBJLoader } from 'OBJLoader';
import { MTLLoader } from 'MTLLoader';
import { STATES, getRollTotal, resolvePassBet, resolveDontPassBet, establishPoint, settleWager } from './rules.js';

const SAVE_KEY = 'cheesborough-street-craps-v1';
const params = { numberOfDice: 2, segments: 30, edgeRadius: .07, notchRadius: .12, notchDepth: .1 };
const diceArray = [];
let renderer, scene, camera, physicsWorld, controls, stableCnt = 0;
let game = null;
const $ = (id) => document.getElementById(id);
const els = { menu: $('lobby'), content: $('game'), playerInput: $('player-input'), nameInputs: $('name-inputs'), roster: $('ai-roster'), menuMessage: $('menu-message'), play: $('play-btn'), resume: $('resume-btn'), return: $('return-btn'), roll: $('roll-btn'), newRound: $('new-round-btn'), wager: $('wager-input'), clear: $('clear-bet'), shooter: $('shooter-name'), balance: $('balance'), wagerDisplay: $('wager-display'), dice: $('dice-values'), total: $('roll-total'), status: $('status-message'), roundState: $('round-state'), players: $('players-list'), history: $('roll-history'), accountBalance: $('account-balance'), accountStatus: $('account-status'), liveStatus: $('live-status'), liveTables: $('live-tables') };
const AI_ROSTER = ['Marcus "Mack" Holloway','Leon "Red" Carter','Calvin "Keys" Mercer','Tasha Monroe','Jerome Tate','Renee "Ray" Carter','Victor Salazar','Elijah Boone'];

function newGame(names) { return { players: names.map((entry) => typeof entry === 'string' ? ({ name: entry.trim() || 'Player', balance: 1000, wins: 0, losses: 0, isAI: false }) : entry), shooterIndex: 0, state: STATES.WAITING_FOR_BET, wager: 0, betSide: 'PASS', point: null, lastDiceValues: [], lastRollTotal: null, roundResult: '', rollHistory: [], isRolling: false, roundActive: false }; }
function validSavedGame(data) { return data && Array.isArray(data.players) && data.players.length >= 1 && data.players.length <= 7 && Number.isInteger(data.shooterIndex) && Object.values(STATES).includes(data.state); }
function saveGame() { if (game) localStorage.setItem(SAVE_KEY, JSON.stringify(game)); }
function loadGame() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY)); return validSavedGame(saved) ? saved : null; } catch { return null; } }
function activePlayer() { return game.players[game.shooterIndex]; }
function formatChips(value) { return `${Number(value || 0).toLocaleString()} chips`; }
function diceFace(value) { return ['⚀','⚁','⚂','⚃','⚄','⚅'][value - 1] || '—'; }
function inputWager() { return Number(els.wager.value); }
function isValidWager(value = inputWager()) { return Number.isFinite(value) && Number.isInteger(value) && value > 0 && value <= activePlayer().balance; }

function updateNameInputs() { els.nameInputs.innerHTML = ''; const input = document.createElement('input'); input.placeholder = 'Your name'; input.value = 'Player 1'; input.setAttribute('aria-label', 'Your name'); els.nameInputs.append(input); }
function updateGameUI() {
  if (!game) return; const player = activePlayer(); const canBet = game.state === STATES.WAITING_FOR_BET && !game.isRolling;
  els.shooter.textContent = player.name; els.balance.textContent = formatChips(player.balance); els.wagerDisplay.textContent = formatChips(game.wager); els.dice.textContent = game.lastDiceValues.length ? game.lastDiceValues.map(diceFace).join(' ') : '⚀ ⚀'; els.total.textContent = game.lastRollTotal ?? '—';
  els.status.textContent = game.roundResult || (canBet ? 'Choose a side and place a wager.' : game.state === STATES.POINT_ACTIVE ? `THE POINT IS ${game.point}` : 'Roll the dice.');
  els.roundState.textContent = game.state.replaceAll('_', ' ').toLowerCase();
  document.querySelectorAll('[data-point]').forEach((el) => el.classList.toggle('active', Number(el.dataset.point) === game.point));
  document.querySelectorAll('.bet-side').forEach((el) => { el.classList.toggle('selected', el.dataset.side === game.betSide); el.disabled = !canBet; });
  document.querySelectorAll('[data-bet]').forEach((el) => el.disabled = !canBet); els.wager.disabled = !canBet; els.clear.disabled = !canBet;
  els.roll.disabled = game.isRolling || (game.state === STATES.WAITING_FOR_BET ? !isValidWager() : !(game.state === STATES.COME_OUT || game.state === STATES.POINT_ACTIVE) || !game.roundActive);
  els.newRound.disabled = game.state !== STATES.ROUND_OVER || game.isRolling;
  els.players.innerHTML = game.players.map((p, i) => `<div class="player-row ${i === game.shooterIndex ? 'shooter' : ''}"><strong>${i === game.shooterIndex ? '◆ ' : ''}${escapeHtml(p.name)}</strong><small>${formatChips(p.balance)}</small><small>${i === game.shooterIndex && game.wager ? `${game.betSide === 'PASS' ? 'PASS' : 'DON’T PASS'} ${game.wager}` : '—'}</small><small>W ${p.wins} / L ${p.losses}</small></div>`).join('');
  els.history.innerHTML = game.rollHistory.map((roll) => `<li>${escapeHtml(roll)}</li>`).join(''); saveGame();
}
function escapeHtml(text) { const node = document.createElement('span'); node.textContent = text; return node.innerHTML; }
function setWager(value) { if (!game || game.state !== STATES.WAITING_FOR_BET) return; els.wager.value = Number.isFinite(value) && value > 0 ? Math.min(Math.floor(value), activePlayer().balance) : ''; game.wager = isValidWager() ? inputWager() : 0; updateGameUI(); }
function startRound() { const wager = inputWager(); if (!isValidWager(wager)) { game.roundResult = 'Enter a whole-chip wager within the shooter’s balance.'; updateGameUI(); return false; } game.wager = wager; game.state = STATES.COME_OUT; game.roundActive = true; game.roundResult = 'Come-out roll. Both dice roll together.'; updateGameUI(); return true; }
function establishNewPoint(total) { game.point = establishPoint(total); game.state = STATES.POINT_ACTIVE; game.roundResult = `THE POINT IS ${game.point}`; }
function rotateShooter() { game.shooterIndex = (game.shooterIndex + 1) % game.players.length; }
function endRound(outcome, result) { settleWager(activePlayer(), game.wager, outcome); game.roundResult = result.message; game.state = STATES.ROUND_OVER; game.roundActive = false; game.point = null; if (result.sevenOut) rotateShooter(); saveGame(); updateGameUI(); if (activePlayer().isAI) window.setTimeout(()=>{ if(game?.state===STATES.ROUND_OVER){resetRound();scheduleAI();}},1100); }
function resolveRoll(values) { if (!values.every((v) => Number.isInteger(v) && v >= 1 && v <= 6)) { game.roundResult = 'Dice did not settle cleanly. Roll again.'; game.isRolling = false; updateGameUI(); return; } const total = getRollTotal(values); game.lastDiceValues = values; game.lastRollTotal = total; let result = game.state === STATES.COME_OUT ? (game.betSide === 'PASS' ? resolvePassBet(total, null, STATES.COME_OUT) : resolveDontPassBet(total, null, STATES.COME_OUT)) : (game.betSide === 'PASS' ? resolvePassBet(total, game.point, STATES.POINT_ACTIVE) : resolveDontPassBet(total, game.point, STATES.POINT_ACTIVE));
  game.rollHistory.unshift(`${values.join(' + ')} = ${total} — ${result.message}`); game.isRolling = false;
  if (result.outcome === 'point') establishNewPoint(total); else if (result.outcome === 'continue') game.roundResult = result.message; else endRound(result.outcome, result); updateGameUI(); }
function resetRound() { if (game.state !== STATES.ROUND_OVER) return; game.state = STATES.WAITING_FOR_BET; game.wager = 0; game.betSide = 'PASS'; game.point = null; game.lastDiceValues = []; game.lastRollTotal = null; game.roundResult = 'New round. Choose a side and wager.'; els.wager.value = ''; updateGameUI(); }

function throwDice() { if (!game || game.isRolling) return; if (game.state === STATES.WAITING_FOR_BET && !startRound()) return; if (!(game.state === STATES.COME_OUT || game.state === STATES.POINT_ACTIVE)) return; game.isRolling = true; stableCnt = 0; game.roundResult = 'Dice are rolling…'; updateGameUI(); diceArray.forEach((die, index) => throwDie(die, index)); }
function throwDie(die, index) { die.body.velocity.setZero(); die.body.angularVelocity.setZero(); die.body.position.set(5, index * 1.5 + 10, 0); die.mesh.position.copy(die.body.position); die.mesh.rotation.set(2 * Math.PI * Math.random(), 0, 2 * Math.PI * Math.random()); die.body.quaternion.copy(die.mesh.quaternion); die.body.applyImpulse(new CANNON.Vec3(-(5 + 25 * Math.random()), -(5 + 25 * Math.random()), 0), new CANNON.Vec3(0, Math.random(), Math.random())); die.body.allowSleep = true; }
function calculateValue(die) { const euler = new CANNON.Vec3(); die.body.quaternion.toEuler(euler); const eps = .1, zero = (a) => Math.abs(a) < eps, half = (a) => Math.abs(a - Math.PI / 2) < eps, minusHalf = (a) => Math.abs(a + Math.PI / 2) < eps, pi = (a) => Math.abs(Math.abs(a) - Math.PI) < eps; if (zero(euler.z)) { if (zero(euler.x)) return 1; if (half(euler.x)) return 4; if (minusHalf(euler.x)) return 3; if (pi(euler.x)) return 6; } else if (half(euler.z)) return 2; else if (minusHalf(euler.z)) return 5; return null; }
function addDiceEvents(die) { die.body.addEventListener('sleep', (event) => { die.body.allowSleep = false; if (!game?.isRolling) return; const value = calculateValue(die); if (!value) { die.body.allowSleep = true; throwDie(die, diceArray.indexOf(die)); return; } stableCnt++; if (stableCnt === diceArray.length) resolveRoll(diceArray.map(calculateValue)); }); }

function initPhysics() { physicsWorld = new CANNON.World({ allowSleep: true, gravity: new CANNON.Vec3(0, -50, 0) }); physicsWorld.defaultContactMaterial.restitution = .3; }
function initScene() { const canvas = $('canvas'); renderer = new THREE.WebGLRenderer({ alpha:true, antialias:true, canvas }); renderer.shadowMap.enabled = true; renderer.setPixelRatio(Math.min(window.devicePixelRatio,2)); scene = new THREE.Scene(); camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, .1, 100); camera.position.set(0,30,30); controls = new OrbitControls(camera, renderer.domElement); controls.enablePan = false; controls.enableDamping = true; controls.minDistance = 1; controls.maxDistance = 40; const ambient = new THREE.AmbientLight(0xffffff,.5); scene.add(ambient); const light = new THREE.PointLight(0xffffff,.5); light.position.set(10,15,0); light.castShadow = true; light.shadow.mapSize.set(2048,2048); scene.add(light); createBorders(); for (let i=0;i<params.numberOfDice;i++) { const die = createDice(i); diceArray.push(die); addDiceEvents(die); } resize(); render(); }
function createBorders() { const material = new THREE.ShadowMaterial({opacity:.1}); const floor = new THREE.Mesh(new THREE.PlaneGeometry(13,13),material); floor.receiveShadow=true; floor.quaternion.setFromAxisAngle(new THREE.Vector3(-1,0,0),Math.PI/2); scene.add(floor); const edge = new THREE.LineSegments(new THREE.EdgesGeometry(floor.geometry),new THREE.LineBasicMaterial({color:0xc69a45})); edge.rotation.x=-Math.PI/2; edge.position.y=.01; scene.add(edge); const body = new CANNON.Body({type:CANNON.Body.STATIC,shape:new CANNON.Plane()}); body.quaternion.copy(floor.quaternion); physicsWorld.addBody(body); [[-7,0,true],[7,0,true],[0,-7,false],[0,7,false]].forEach(([x,z,parallel]) => { const mesh = new THREE.Mesh(new THREE.BoxGeometry(parallel?1:14,15,parallel?14:1),material); mesh.position.set(x,7.5,z); scene.add(mesh); const wall = new CANNON.Body({type:CANNON.Body.STATIC,shape:new CANNON.Box(new CANNON.Vec3(parallel?.5:7,7.5,parallel?7:.5))}); wall.position.copy(mesh.position); physicsWorld.addBody(wall); }); }
function createDiceMesh(id) { const group = new THREE.Group(); new MTLLoader().load('dice.mtl',(materials)=>{ materials.preload(); const loader=new OBJLoader(); loader.setMaterials(materials); loader.load('dice.obj',(object)=>{ object.traverse((child)=>{if(child instanceof THREE.Mesh) child.castShadow=true;}); object.rotation.set(0,Math.PI/2,0); const size=new THREE.Vector3(); new THREE.Box3().setFromObject(object).getSize(size); object.scale.set(1.05/size.x,1.05/size.y,1.05/size.z); group.add(object); },undefined,()=>console.error('Could not load dice model')); }); return group; }
function createDice(id) { const mesh=createDiceMesh(id); scene.add(mesh); const body=new CANNON.Body({mass:1,shape:new CANNON.Box(new CANNON.Vec3(.5,.5,.5)),sleepTimeLimit:.1}); physicsWorld.addBody(body); return {mesh,body,id}; }
function render() { physicsWorld.fixedStep(); diceArray.forEach((die)=>{die.mesh.position.copy(die.body.position);die.mesh.quaternion.copy(die.body.quaternion);}); controls.update(); renderer.render(scene,camera); requestAnimationFrame(render); }
function resize() { camera.aspect=innerWidth/innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth,innerHeight); }

function scheduleAI() { if (!game || game.isRolling || !activePlayer().isAI) return; window.setTimeout(() => { if (!game || !activePlayer().isAI || game.isRolling) return; if (game.state === STATES.WAITING_FOR_BET) { game.betSide = Math.random() < .8 ? 'PASS' : 'DONT_PASS'; setWager(Math.min(activePlayer().balance, [10,25,50][Math.floor(Math.random()*3)])); } if (game.state === STATES.WAITING_FOR_BET || game.state === STATES.COME_OUT || game.state === STATES.POINT_ACTIVE) throwDice(); }, 850); }
async function refreshLobby() { els.accountBalance.textContent='1,000 chips at every seat'; els.accountStatus.textContent='Your signed-in Games Desk account unlocks every game. Every Street Dice player begins this game with 1,000 virtual chips.'; els.liveStatus.textContent='Choose the people at your table. Named AI shooters take their own turns.'; els.liveTables.textContent=''; }
els.playerInput.addEventListener('input',updateNameInputs); els.play.addEventListener('click',()=>{ const saved=loadGame(); if(saved && !confirm('Start a new game? This clears the saved game.')) return; localStorage.removeItem(SAVE_KEY); const count=Math.min(7,Math.max(2,Number(els.playerInput.value)||2)); const selected=[...els.roster.selectedOptions].slice(0,count-1).map((opt)=>({name:opt.value,balance:1000,wins:0,losses:0,isAI:true})); if(selected.length!==count-1){els.menuMessage.textContent=`Choose ${count-1} named AI opponent${count===2?'':'s'} for this ${count}-player game.`;return;} const human={name:els.nameInputs.querySelector('input').value.trim()||'Player 1',balance:1000,wins:0,losses:0,isAI:false}; game=newGame([human,...selected]); els.menu.classList.add('hidden'); els.content.classList.remove('hidden'); updateGameUI(); scheduleAI(); });
els.resume.addEventListener('click',()=>{ game=loadGame(); if(!game) return; game.isRolling=false; els.menu.classList.add('hidden'); els.content.classList.remove('hidden'); updateGameUI(); scheduleAI(); }); els.return.addEventListener('click',()=>{ saveGame(); els.content.classList.add('hidden'); els.menu.classList.remove('hidden'); refreshLobby(); }); els.roll.addEventListener('click',throwDice); els.newRound.addEventListener('click',()=>{resetRound();scheduleAI();}); els.wager.addEventListener('input',()=>setWager(inputWager())); els.clear.addEventListener('click',()=>setWager(0)); document.querySelectorAll('.bet-side').forEach((button)=>button.addEventListener('click',()=>{if(game.state===STATES.WAITING_FOR_BET){game.betSide=button.dataset.side;updateGameUI();}})); document.querySelectorAll('[data-bet]').forEach((button)=>button.addEventListener('click',()=>setWager(button.dataset.bet==='MAX'?activePlayer().balance:Number(button.dataset.bet))));
AI_ROSTER.forEach((name)=>{const option=document.createElement('option');option.value=name;option.textContent=name;els.roster.append(option);}); updateNameInputs(); if(loadGame()) els.resume.classList.remove('hidden'); refreshLobby(); initPhysics(); initScene(); addEventListener('resize',resize);
