document.addEventListener('DOMContentLoaded', async () => {
  const community = window.CCCCommunity, status = document.querySelector('#profile-status'), form = document.querySelector('#profile-form');
  const input = document.querySelector('#profile-avatar-input'), image = document.querySelector('#profile-avatar-preview'), fallback = document.querySelector('#profile-avatar-initials'), remove = document.querySelector('#profile-avatar-remove'), avatarHelp = document.querySelector('#profile-avatar-help'), logout = document.querySelector('#profile-logout');
  const interests = ['True Crime', 'Unsolved Cases', 'Cold Cases', 'Prison Stories', 'Gang History', 'Famous Trials', 'Historical Crime', 'Missing Persons', 'Criminal Justice', 'Courtroom Stories', 'Crime Documentaries', 'Forensics', 'Wrongful Convictions', 'Juvenile Justice']; let selectedInterests = [];
  let user = await community.restoreSession(); if (!user) { location.replace('LOGIN.html?returnTo=%2FPROFILE.html'); return; }
  logout?.addEventListener('click', () => community.logout());
  avatarHelp.textContent = 'JPG, PNG, or WebP. New uploads crop to fill the circular profile frame.';
  const field = (name) => form.elements.namedItem(name);
  const setAvatar = () => { const source = community.avatarUrl(user); fallback.textContent = community.initials(user.displayName); fallback.hidden = Boolean(source); image.hidden = !source; image.src = source || ''; remove.hidden = !source; remove.disabled = !source; };
  const count = (inputId, outputId) => { document.querySelector(outputId).textContent = document.querySelector(inputId).value.length; };
  const clearErrors = () => form.querySelectorAll('.field-error').forEach((node) => node.remove());
  const showError = (control, message) => { if (!control) return; control.setAttribute('aria-invalid', 'true'); const error = document.createElement('p'); error.className = 'field-error'; error.textContent = message; control.closest('label')?.append(error); };
  form.addEventListener('invalid', (event) => { event.preventDefault(); clearErrors(); const control = event.target; showError(control, control.name === 'username' ? 'Use 3-24 letters, numbers, or underscores for your @handle.' : control.validationMessage); control.focus(); }, true);
  const renderInterests = () => { const host = document.querySelector('#profile-interests'); host.textContent = ''; interests.forEach((interest) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'interest-chip'; button.textContent = interest; button.setAttribute('aria-pressed', String(selectedInterests.includes(interest))); button.addEventListener('click', () => { if (selectedInterests.includes(interest)) selectedInterests = selectedInterests.filter((item) => item !== interest); else if (selectedInterests.length < 10) selectedInterests.push(interest); else { status.textContent = 'Choose up to 10 interests.'; return; } renderInterests(); }); host.append(button); }); };
  const addFavorite = (value = '') => { const row = document.createElement('div'); row.className = 'favorite-row'; const item = document.createElement('input'); item.type = 'text'; item.maxLength = 80; item.value = value; item.placeholder = 'Case or story title'; item.setAttribute('aria-label', 'Favorite case or story'); const deleteButton = document.createElement('button'); deleteButton.type = 'button'; deleteButton.className = 'favorite-remove'; deleteButton.textContent = 'Remove'; deleteButton.addEventListener('click', () => row.remove()); row.append(item, deleteButton); document.querySelector('#profile-favorites').append(row); };
  document.querySelector('#profile-display-name').textContent = user.displayName; document.querySelector('#profile-email').textContent = 'Your email address is private.'; field('displayName').value = user.displayName; setAvatar(); renderInterests();
  [['#profile-about', '#profile-about-count'], ['#profile-now', '#profile-now-count']].forEach(([source, output]) => document.querySelector(source).addEventListener('input', () => count(source, output)));
  document.querySelector('#profile-add-favorite').addEventListener('click', () => document.querySelectorAll('.favorite-row').length < 10 ? addFavorite() : status.textContent = 'You can save up to 10 favorites.');
  try { const profile = (await community.request('/api/auth/profile')).profile || {}; Object.entries(profile).forEach(([key, value]) => { const control = field(key); if (control && typeof value === 'string') control.value = value; }); selectedInterests = Array.isArray(profile.interests) ? profile.interests.filter((item) => interests.includes(item)).slice(0, 10) : []; (profile.favorites || []).slice(0, 10).forEach(addFavorite); renderInterests(); count('#profile-about', '#profile-about-count'); count('#profile-now', '#profile-now-count'); } catch { status.textContent = 'Your profile details could not load yet. You can still update them.'; }
  const resizeImage = (file) => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(Error('The selected image could not be read.')); reader.onload = () => { const photo = new Image(); photo.onerror = () => reject(Error('The selected file is not a supported image.')); photo.onload = () => { const shortestSide = Math.min(photo.naturalWidth, photo.naturalHeight), canvasSize = Math.min(800, shortestSide), scale = canvasSize / shortestSide, width = Math.max(1, Math.round(photo.naturalWidth * scale)), height = Math.max(1, Math.round(photo.naturalHeight * scale)), canvas = document.createElement('canvas'), context = canvas.getContext('2d'); canvas.width = canvasSize; canvas.height = canvasSize; context.drawImage(photo, Math.round((canvasSize - width) / 2), Math.round((canvasSize - height) / 2), width, height); resolve(canvas.toDataURL('image/jpeg', 0.88)); }; photo.src = reader.result; }; reader.readAsDataURL(file); });
  input.addEventListener('change', async () => { const file = input.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 12 * 1024 * 1024) { status.textContent = 'Choose a JPG, PNG, or WebP image smaller than 12 MB.'; input.value = ''; return; } status.textContent = 'Preparing your profile photo...'; try { const payload = await community.request('/api/auth/avatar', { method: 'POST', body: JSON.stringify({ imageData: await resizeImage(file) }) }); user = { ...user, avatarUpdatedAt: payload.avatarUpdatedAt }; setAvatar(); community.renderNav(user); status.textContent = 'Your profile photo has been saved.'; } catch (error) { status.textContent = error.message; } input.value = ''; });
  remove.addEventListener('click', async () => { remove.disabled = true; try { await community.request('/api/auth/avatar', { method: 'DELETE' }); user = { ...user, avatarUpdatedAt: null }; setAvatar(); community.renderNav(user); status.textContent = 'Your profile photo has been removed.'; } catch (error) { status.textContent = error.message; } remove.disabled = false; });
  form.addEventListener('submit', async (event) => { event.preventDefault(); clearErrors(); form.querySelectorAll('[aria-invalid]').forEach((node) => node.removeAttribute('aria-invalid')); const data = Object.fromEntries(new FormData(form)); data.interests = selectedInterests; data.favorites = [...document.querySelectorAll('.favorite-row input')].map((node) => node.value.trim()).filter(Boolean); status.textContent = 'Saving your profile...'; try { const payload = await community.request('/api/auth/profile', { method: 'PUT', body: JSON.stringify(data) }); user = { ...user, displayName: payload.user.displayName }; document.querySelector('#profile-display-name').textContent = user.displayName; setAvatar(); community.renderNav(user); status.textContent = 'Your profile has been saved.'; } catch (error) { const message = error.message || 'Your profile could not be saved.'; const control = /display name/i.test(message) ? field('displayName') : /username/i.test(message) ? field('username') : /links|http/i.test(message) ? form.querySelector('input[type="url"]:invalid') || form.querySelector('input[type="url"]') : null; if (control) { showError(control, message); control.focus(); } status.textContent = message; } });
});
