from pathlib import Path
import json,html,re,math
ROOT=Path(__file__).resolve().parents[1];content=json.loads((ROOT/'data/mama-herc-article.json').read_text(encoding='utf-8-sig'));esc=lambda x:html.escape(str(x),quote=True)
photo='01_Photos/02_By-State/Florida/MamaHerc.png'
credit='Photograph by Charles Norman, 1985. Reproduced in <em>Journal of Prisoners on Prisons</em> 19(1), 2010, p. 47.'
paragraphs=lambda xs:''.join(x if re.match(r'\s*<(?:p|blockquote|ul|ol)\b',x) else '<p>'+x+'</p>' for x in xs)
chapters=content['chapters'];nav=''.join(f'<li><a href="#{esc(c["id"])}"><span>{i:02}</span>{esc(c["title"])}</a></li>' for i,c in enumerate(chapters,1))
body=[]
for i,c in enumerate(chapters,1):
 fig=f'<figure class="mh-photo-interlude"><a href="{photo}" data-open-photo><img src="{photo}" alt="Mama Herc smiling and flexing his arm" width="758" height="581" loading="lazy"></a><figcaption>{credit} <a href="{photo}" data-open-photo>Open The Full Photograph &#8599;</a></figcaption></figure>' if c['id']=='the-photograph' else ''
 pull=f'<blockquote class="mh-pullquote">{esc(c["pullQuote"])}</blockquote>' if c.get('pullQuote') else ''
 body.append(f'<section class="mh-chapter" id="{esc(c["id"])}"><h2><span class="mh-chapter-number">{i:02} / The Story</span>{esc(c["title"])}</h2>{fig}{paragraphs(c["paragraphs"])}{pull}</section>')
words=len(re.findall(r"\b[\w'-]+\b",re.sub('<[^>]+>',' ',paragraphs(content.get('opening',[]))+''.join(paragraphs(c['paragraphs']) for c in chapters))))
minutes=max(1,math.ceil(words/220))
sources=''.join(f'<li id="{esc(s.get("id","source-"+str(i)))}"><a href="{esc(s["url"])}" target="_blank" rel="noopener">{esc(s["title"])} &#8599;</a><p>{s.get("note","")}</p></li>' for i,s in enumerate(content['sources'],1))
videos=''.join(f'<article class="mh-video"><h3>{esc(v["title"])}</h3><div class="mh-video-frame" data-video-id="{esc(v["id"])}" data-video-title="{esc(v["title"])}"><a class="mh-video-thumbnail" href="https://www.youtube.com/watch?v={esc(v["id"])}" aria-label="Watch {esc(v["title"])} on YouTube"><img src="https://i.ytimg.com/vi/{esc(v["id"])}/hqdefault.jpg" width="480" height="360" loading="lazy" alt="Video thumbnail for {esc(v["title"])}"><span class="mh-video-play-label"><span aria-hidden="true">&#9654;</span> Play Video</span></a></div><p>{esc(v.get("description",""))}</p><a href="https://www.youtube.com/watch?v={esc(v["id"])}" target="_blank" rel="noopener">Watch On YouTube &#8599;</a></article>' for v in content.get('videos',[]))
videoSection=f'<section class="mh-video-section" id="related-videos"><p class="mh-kicker">In Their Own Telling</p><h2>More Voices, More Stories</h2><p>These videos offer another way into the stories. Choose a video to load its player, or watch on YouTube.</p>{videos}</section>' if videos else ''
title=content['title'];deck=content['deck'];heading=esc(title).replace('The Jar Of Gold Teeth','<em>The Jar Of Gold Teeth</em>')
markup=f'''<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | Carceral Collections</title><meta name="description" content="{esc(deck)}"><link rel="canonical" href="https://carceralcollections.org/MAMA-HERC.html"><meta property="og:type" content="article"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(deck)}"><meta property="og:image" content="https://carceralcollections.org/{photo}"><meta property="og:url" content="https://carceralcollections.org/MAMA-HERC.html"><meta name="twitter:card" content="summary_large_image"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&amp;family=Source+Sans+3:wght@400;600;700&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="mama-herc.css?v=20260908-thumbnails"><script src="mama-herc.js?v=20260908-thumbnails" defer></script><script src="site-analytics.js" defer></script><script src="community-auth.js" defer></script><script src="article-comments.js?v=20260908-comments" defer></script></head>
<body class="mh-page"><a class="mh-skip" href="#mh-article">Skip To The Story</a><div class="mh-progress" aria-hidden="true"><span data-reading-progress></span></div>
<header class="mh-header"><a class="mh-brand" href="index.html">Cheesborough Carceral Collections</a><nav aria-label="Primary navigation"><a href="index.html">Home</a><a href="COLLECTIONS.html">Collections</a><a href="CONTACT.html">Contact</a></nav></header>
<main><section class="mh-lead" aria-labelledby="mh-title"><div class="mh-edition"><span>The Latest Feature</span><span>Florida Prison Legends</span></div><div class="mh-hero-grid"><div><p class="mh-kicker">Mama Herc / K-Wing Slim / Nigger Charlie / Gold Teeth</p><h1 id="mh-title">{heading}</h1><p class="mh-deck">{esc(deck)}</p><p class="mh-byline">By <strong>Cheesborough Carceral Collections</strong><br><time datetime="2026-09-08">September 8, 2026</time> &middot; {minutes} Minute Read</p></div><figure class="mh-hero-photo"><a href="{photo}" data-open-photo aria-label="Open the full photograph of Mama Herc"><img src="{photo}" width="758" height="581" alt="Mama Herc smiling and flexing his arm, wearing a headwrap and beads"><span class="mh-photo-open">The Full Photograph &#8599;</span></a><figcaption>{credit}</figcaption></figure></div><div class="mh-lead-bottom"><a href="#mh-article">Let&rsquo;s Get Into It <span aria-hidden="true">&#8595;</span></a><a class="mh-join-link" href="#comments">Join The Conversation <span aria-hidden="true">&#8595;</span></a><button class="mh-share" type="button" data-share-story hidden>Share This Story &#8599;</button></div><p class="mh-share-status" role="status" data-share-status></p><input class="mh-copy-link" data-copy-link aria-label="Story link to copy" readonly hidden></section>
<div class="mh-story-layout"><aside class="mh-chapters"><details open><summary>Find Your Place</summary><ol>{nav}</ol><a class="mh-rail-conversation" href="#comments">Join The Conversation &#8595;</a><a class="mh-rail-sources" href="#sources">The Sources &#8595;</a></details></aside><article class="mh-article" id="mh-article"><div class="mh-opening">{paragraphs(content.get('opening',[]))}</div>{''.join(body)}{videoSection}<section class="mh-conversation" id="comments" aria-labelledby="mh-comments-title"><div class="mh-conversation-heading"><p class="mh-kicker">Your Turn</p><h2 id="mh-comments-title">The Conversation Continues</h2></div><div data-community-comments data-resource-id="mama-herc" data-comment-title="Join The Conversation" data-comment-placeholder="Add your comment..."><p>Sign in to join the public conversation. Comments appear after moderation.</p><a class="community-comment-signin" href="LOGIN.html?returnTo=%2FMAMA-HERC.html">Sign In To Comment</a></div><p class="mh-conversation-contact"><a href="CONTACT.html">Contact Us Privately</a></p></section><section class="mh-sources" id="sources"><h2>Where The Stories Come From</h2><ol>{sources}</ol></section></article></div></main><footer class="mh-footer"><a href="index.html">Cheesborough Carceral Collections</a></footer><dialog class="mh-photo-dialog" id="mh-photo-dialog" aria-label="Full photograph of Mama Herc"><button type="button">Close Photograph &times;</button><img src="{photo}" width="758" height="581" alt="Full photograph of Mama Herc flexing his arm"><p>{credit}</p></dialog></body></html>'''
(ROOT/'MAMA-HERC.html').write_text(markup,encoding='utf-8');print('Generated MAMA-HERC.html',len(chapters),'chapters',words,'narrative words',minutes,'minutes')
